
# Grouping #
TRAINING_BATCH_SIZE = 100
EPISODE_BATCH_SIZE = 100
N_WAY=5

# Training #
EPISODES=30
SCORING_THRESHOLD = 1.3

TRAINING_LOOPS=10
EPOCHS = 1

SAMPLE_SIZE = 1000
MIN_MEMORIES = 3000
MAX_MEMORIES = 30000

# Optimizer #
LR = .1
OPTIM = "Adam"
MOMENTUM = .9
WEIGHT_DECAY = 0.0001

# Shape #
CH = 3
R = 6
C = 7

SHAPE = (CH, R, C)

TRAINING_BATCH_SHAPE = (TRAINING_BATCH_SIZE, CH, R, C)
EPISODE_BATCH_SHAPE = (EPISODE_BATCH_SIZE, CH, R, C)

###
#Model Config
###
NUM_RES_BLOCKS = 4
NUM_STATE_RES_BLOCKS = NUM_RES_BLOCKS
NUM_Q_RES_BLOCKS = NUM_RES_BLOCKS
NUM_P_RES_BLOCKS = NUM_RES_BLOCKS

NUM_RES_FILTERS = 32
NUM_STATE_RES_FILTERS = NUM_RES_FILTERS
NUM_Q_RES_FILTERS = NUM_RES_FILTERS
NUM_P_RES_FILTERS = NUM_RES_FILTERS
