
# Grouping #
BATCH_SIZE = 120
TRAINING_BATCH_SIZE = BATCH_SIZE
EPISODE_BATCH_SIZE = 40
N_WAY=5

# Training #
# EPISODES=30
SCORING_THRESHOLD = 1.2

TRAINING_LOOPS = 10
EPOCHS = 5 #1

SAMPLE_SIZE = 1000//N_WAY
MIN_TASK_MEMORIES = 3000//N_WAY
MAX_TASK_MEMORIES = 30000//N_WAY

# Optimizer #
LR = .001 #.03
OPTIM = "sgd"
MOMENTUM = .9
WEIGHT_DECAY = 0.000001

# Shape #
CH = 3
R = 6
C = 7

SHAPE = (CH, R, C)

TRAINING_BATCH_SHAPE = (TRAINING_BATCH_SIZE, CH, R, C)
EPISODE_BATCH_SHAPE = (EPISODE_BATCH_SIZE, CH, R, C)

###
#Model Config
###
CUDA=False

Q_UPDATES_PER = 1

NUM_RES_BLOCKS = 6
NUM_STATE_RES_BLOCKS = NUM_RES_BLOCKS
NUM_Q_RES_BLOCKS = NUM_RES_BLOCKS
NUM_P_RES_BLOCKS = NUM_RES_BLOCKS

NUM_RES_FILTERS = 40
NUM_STATE_RES_FILTERS = NUM_RES_FILTERS
NUM_Q_RES_FILTERS = NUM_RES_FILTERS
NUM_P_RES_FILTERS = NUM_RES_FILTERS

POLICY_HEAD_FILTERS = 2
