
# Grouping #
BATCH_SIZE = 15*10
TRAINING_BATCH_SIZE = 240
EPISODE_BATCH_SIZE = BATCH_SIZE
N_WAY=15

# Training #
# EPISODES=30
SCORING_THRESHOLD = 1.3

#Q_TRAINING_LOOPS = 100
#P_TRAINING_LOOPS = 100
SELF_PLAY_POLICY_LOOPS = 3

TRAINING_LOOPS = 50
EPOCHS = 1 #5 

MIN_TASK_MEMORIES = 500
MAX_TASK_MEMORIES = 30000

# Optimizer #
LR = .001 #.03
OPTIM = "sgd"
MOMENTUM = .9
WEIGHT_DECAY = 0.0001

# Shape #
CH = 3
R = 6
C = 7

SHAPE = (CH, R, C)

TRAINING_BATCH_SHAPE = (TRAINING_BATCH_SIZE, CH, R, C)
EPISODE_BATCH_SHAPE = (EPISODE_BATCH_SIZE, CH, R, C)

###
#Model Config
###
CUDA=False

Q_UPDATES_PER = 1

NUM_RES_BLOCKS = 6
NUM_STATE_RES_BLOCKS = NUM_RES_BLOCKS
NUM_Q_RES_BLOCKS = NUM_RES_BLOCKS
NUM_P_RES_BLOCKS = NUM_RES_BLOCKS

NUM_RES_FILTERS = 60
NUM_STATE_RES_FILTERS = NUM_RES_FILTERS
NUM_Q_RES_FILTERS = NUM_RES_FILTERS
NUM_P_RES_FILTERS = NUM_RES_FILTERS

POLICY_HEAD_FILTERS = 2
